theme: jekyll-theme-slate
title: Bioinformatics Hub of Kenya Intiative Seminar Series
description: Empowering our community with Bioinformatics, Data Management and Research Software Development Skills  
