theme: jekyll-theme-slate
title: Bioinformatics Hub of Kenya Intiative Seminar Series
description: Empowering our community with bionformatics, and research software development skills  
avatar: /images/Bioinformatica_Hub_Logo.png
